### ISSUE TITLE
Dropping a Future can cause a BorrowMutError

### ISSUE THREAD

**Issue by antoyo** [tokio-rs/tokio-core#190]
Hello.
I found a case where dropping a `Future` can panic with a `BorrowMutError`.
I didn't have the time to produce a small example to reproduce this issue (sorry), but if you comment [this line](https://github.com/antoyo/relm/blob/f999ca5df0c3e40b91a6aebfb8a877d8a5c43e27/src/lib.rs#L166), the future will be dropped when calling the `exec` method.
After commenting this line, run the `clock` example and you will get the following error:
```
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', /checkout/src/libcore/result.rs:860
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:761
   1: <core::cell::RefCell<T>>::borrow_mut
             at /checkout/src/libcore/cell.rs:740
   2: tokio_core::reactor::Core::consume_queue
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:400
   3: tokio_core::reactor::Remote::send::{{closure}}
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:552
   4: tokio_core::reactor::Remote::with_loop::{{closure}}
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:576
   5: <scoped_tls::ScopedKey<T>>::with
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:169
   6: tokio_core::reactor::Remote::with_loop
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:573
   7: tokio_core::reactor::Remote::send
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:547
   8: tokio_core::reactor::timeout_token::TimeoutToken::cancel_timeout
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/timeout_token.rs:54
   9: <tokio_core::reactor::interval::Interval as core::ops::Drop>::drop
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/interval.rs:80
  10: drop
  11: drop
  12: drop
  13: drop
  14: <relm::Relm<M>>::exec
             at ./src/lib.rs:167
  15: <relm::Relm<M>>::connect_exec
             at ./src/lib.rs:162
  16: <clock::Win as relm::widget::Widget<clock::Msg>>::subscriptions
             at ./examples/clock.rs:91
  17: <relm::Relm<M>>::run::{{closure}}
             at ./src/lib.rs:185
  18: tokio_core::reactor::Remote::spawn::{{closure}}
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:600
  19: <F as tokio_core::reactor::FnBox>::call_box
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:708
  20: tokio_core::reactor::Core::notify
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:429
  21: tokio_core::reactor::Core::consume_queue
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:401
  22: tokio_core::reactor::Core::poll::{{closure}}
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:295
  23: <scoped_tls::ScopedKey<T>>::set
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  24: tokio_core::reactor::Core::poll
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:295
  25: tokio_core::reactor::Core::turn
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.4/src/reactor/mod.rs:250
  26: relm_core::Core::run::{{closure}}
             at ./relm-core/src/lib.rs:51
  27: <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once
             at /checkout/src/libstd/panic.rs:296
  28: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  29: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  30: std::panicking::try
             at /checkout/src/libstd/panicking.rs:433
  31: std::panic::catch_unwind
             at /checkout/src/libstd/panic.rs:361
  32: std::thread::Builder::spawn::{{closure}}
             at /checkout/src/libstd/thread/mod.rs:360
  33: <F as alloc::boxed::FnBox<A>>::call_box
             at /checkout/src/liballoc/boxed.rs:638
  34: std::sys::imp::thread::Thread::new::thread_start
             at /checkout/src/liballoc/boxed.rs:648
             at /checkout/src/libstd/sys_common/thread.rs:21
             at /checkout/src/libstd/sys/unix/thread.rs:84
  35: start_thread
  36: clone
```
Is this a normal issue?
Thanks.

**Comment by alexcrichton** [comment]
Definitely looks like a bug, thanks for the report!

**Comment by alexcrichton** [comment]
I've managed to reproduce locally and have a small test case, working on a fix.
