### ISSUE TITLE
Timer heap seems to fail on travis

### ISSUE THREAD

**Issue by NeoLegends** [tokio-rs/tokio-core#22]
Currently when I'm running my tests on travis there is a failing `.unwrap()` in the timers `heap.rs`. The error does not occur on my PC.

This is the backtrace (the error occurs [here](https://github.com/tokio-rs/tokio-core/blob/1f0d2198ad1f0f7e7e378debf83e32d0fd5e90bb/src/heap.rs#L71)):

```
thread 'tests::put' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:317
stack backtrace:
   1:     0x7f811bcd9423 - std::sys::backtrace::tracing::imp::write::h46f28e67d38b4637
   2:     0x7f811bcdd52d - std::panicking::default_hook::{{closure}}::h1d3243f546573ff4
   3:     0x7f811bcdc6ce - std::panicking::default_hook::h96c288d728df3ebf
   4:     0x7f811bcdcdb8 - std::panicking::rust_panic_with_hook::hb1322e5f2588b4db
   5:     0x7f811bcdcc52 - std::panicking::begin_panic::hfbeda5aad583dc32
   6:     0x7f811bcdcb90 - std::panicking::begin_panic_fmt::h4fe9fb9d5109c4bf
   7:     0x7f811bcdcb11 - rust_begin_unwind
   8:     0x7f811bd1741f - core::panicking::panic_fmt::h4395919ece15c671
   9:     0x7f811bd1734b - core::panicking::panic::hc74ff52ed78364e1
  10:     0x7f811bc2b195 - <core::option::Option<T>>::unwrap::h287745a6792bd9bc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
  11:     0x7f811bc41b8c - <tokio_core::heap::Heap<T>>::remove::hf9d52bc2c83ee1dd
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/heap.rs:71
  12:     0x7f811bc4b365 - tokio_core::reactor::Inner::cancel_timeout::h7772ee9fb74940ad
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:474
  13:     0x7f811bc49676 - tokio_core::reactor::Core::notify::h1adc6d28c9d93874
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:403
  14:     0x7f811bc4ce53 - tokio_core::reactor::Remote::send::{{closure}}::hf960237408f0a20d
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:507
  15:     0x7f811bc4c90b - tokio_core::reactor::Remote::with_loop::{{closure}}::h1832bb427de4d5ea
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:532
  16:     0x7f811bc2e613 - <scoped_tls::ScopedKey<T>>::with::h6e57d5658ba0e9e7
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:169
  17:     0x7f811bc4bcbd - tokio_core::reactor::Remote::with_loop::h86eacd5eb370b9fc
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:529
  18:     0x7f811bc4bb25 - tokio_core::reactor::Remote::send::he982eb09318059e2
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:501
  19:     0x7f811bc44dbc - tokio_core::reactor::timeout_token::TimeoutToken::cancel_timeout::hd3f8329f407351ea
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/timeout_token.rs:55
  20:     0x7f811bc451d7 - <tokio_core::reactor::timeout::Timeout as core::ops::Drop>::drop::h28d6e347297cbdb7
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/timeout.rs:67
  21:     0x7f811bbcaa50 - drop::h8fe4978a28fca4b2
  22:     0x7f811bbc925c - drop::h3ad133ee1ca32f75
  23:     0x7f811bbddeb9 - tokio_curl::imp::Data::check_timeout::h12c04688a420c888
                        at /home/travis/.cargo/git/checkouts/tokio-curl-54e764422eb98a95/master/src/unix.rs:406
  24:     0x7f811bbdf6e5 - <tokio_curl::imp::Data as futures::Future>::poll::{{closure}}::hbf483cb013d7295a
                        at /home/travis/.cargo/git/checkouts/tokio-curl-54e764422eb98a95/master/src/unix.rs:151
  25:     0x7f811bbb33a4 - <scoped_tls::ScopedKey<T>>::set::hddcd333f694d8d33
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  26:     0x7f811bbda5bb - <tokio_curl::imp::Data as futures::Future>::poll::ha5387a9110be3742
                        at /home/travis/.cargo/git/checkouts/tokio-curl-54e764422eb98a95/master/src/unix.rs:134
  27:     0x7f811bbd6327 - <futures::map_err::MapErr<A, F> as futures::Future>::poll::h831b3981182fa89f
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/map_err.rs:29
  28:     0x7f811bc329f1 - <Box<F> as futures::Future>::poll::he02a88e98ecfd367
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/lib.rs:227
  29:     0x7f811bc4c38c - <futures::task::Spawn<F>>::poll_future::{{closure}}::h4247054fe3ce122d
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:217
  30:     0x7f811bc4c3de - <futures::task::Spawn<T>>::enter::{{closure}}::h2ef40e21bf314afa
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:304
  31:     0x7f811bc4cb05 - futures::task::set::{{closure}}::h3868fa6304a605e9
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:75
  32:     0x7f811bc3161a - <std::thread::local::LocalKey<T>>::with::hba1eb31bc1ccce00
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/thread/local.rs:245
  33:     0x7f811bc3eb77 - futures::task::set::hf29ebf4e1badbc96
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:72
  34:     0x7f811bc2c56a - <futures::task::Spawn<T>>::enter::h9098896dd8ba81dd
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:304
  35:     0x7f811bc2c3ea - <futures::task::Spawn<F>>::poll_future::h224b3d5d722c3423
                        at /home/travis/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task/mod.rs:217
  36:     0x7f811bc4c6d6 - tokio_core::reactor::Core::dispatch_task::{{closure}}::h8ba75822601e0ca1
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:337
  37:     0x7f811bc2e43e - <scoped_tls::ScopedKey<T>>::set::hb38bd7bc1a40c86b
                        at /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  38:     0x7f811bc47dcd - tokio_core::reactor::Core::dispatch_task::h85e5ff0bfe787603
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:337
  39:     0x7f811bc47258 - tokio_core::reactor::Core::dispatch::he793b13f3b00750d
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:297
  40:     0x7f811bc46e15 - tokio_core::reactor::Core::_run::h3fb411c1d745048e
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:284
  41:     0x7f811bb459c6 - tokio_core::reactor::Core::run::h5b1951e578df9f55
                        at /home/travis/.cargo/git/checkouts/tokio-core-ec1bf80948dd483b/master/src/reactor/mod.rs:217
  42:     0x7f811bba2e2e - tokio_request::tests::put::h174ca765f7c4fdae
                        at /home/travis/build/NeoLegends/tokio-request/src/lib.rs:257
  43:     0x7f811bc8007b - <F as alloc::boxed::FnBox<A>>::call_box::h8891a5eabeec8e3a
  44:     0x7f811bc7a2f3 - std::panicking::try::do_call::h8b4330db5afa6940
  45:     0x7f811bce4ff6 - __rust_maybe_catch_panic
  46:     0x7f811bc7fee9 - <F as alloc::boxed::FnBox<A>>::call_box::h4eaa9b5ba8675a97
  47:     0x7f811bcdb570 - std::sys::thread::Thread::new::thread_start::h5b631f48cd23f128
  48:     0x7f811ac0ae99 - start_thread
  49:     0x7f811a72236c - <unknown>
```

**Comment by NeoLegends** [comment]
That fixed it. Thanks!
