### ISSUE TITLE
Cannot tokio::spawn from Core::run

### ISSUE THREAD

**Issue by mitsuhiko** [tokio-rs/tokio-core#313]
I expected this to work:

```rust
extern crate futures;
extern crate tokio;
extern crate tokio_core;

use tokio_core::reactor::Core;
use futures::future;
use futures::Future;


fn main() {
    let mut core = Core::new().unwrap();
    core.run(future::lazy(move || -> Result<(), ()> {
        tokio::spawn(future::ok(42)
            .and_then(|x| Ok(println!("{}", x))));
        Ok(())
    })).unwrap();
}
```

However I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', src/libcore/result.rs:916:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:68
             at src/libstd/sys_common/backtrace.rs:57
             at src/libstd/panicking.rs:381
   2: std::panicking::default_hook
             at src/libstd/panicking.rs:397
   3: std::panicking::begin_panic
             at src/libstd/panicking.rs:577
   4: std::panicking::begin_panic
             at src/libstd/panicking.rs:538
   5: std::panicking::try::do_call
             at src/libstd/panicking.rs:522
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:498
   7: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at src/libcore/panicking.rs:71
   8: core::result::unwrap_failed
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:23
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: tokio_executor::global::spawn
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.0/src/global.rs:108
  11: tokio::executor::spawn
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.3/src/executor/mod.rs:205
  12: tokiotest::main::{{closure}}
             at src/main.rs:13
  13: <futures::future::lazy::Lazy<F, R>>::get
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/lazy.rs:64
  14: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/future/lazy.rs:82
  15: <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}}
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  16: <futures::task_impl::Spawn<T>>::enter::{{closure}}
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  17: futures::task_impl::std::set
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/std/mod.rs:78
  18: <futures::task_impl::Spawn<T>>::enter
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:363
  19: <futures::task_impl::Spawn<T>>::poll_future_notify
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.18/src/task_impl/mod.rs:289
  20: tokio_core::reactor::Core::run::{{closure}}
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.14/src/reactor/mod.rs:241
  21: <scoped_tls::ScopedKey<T>>::set
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:155
  22: tokio_core::reactor::Core::run
             at /Users/mitsuhiko/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.14/src/reactor/mod.rs:240
  23: tokiotest::main
             at src/main.rs:12
  24: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  25: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:480
  26: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:101
  27: std::sys_common::bytestring::debug_fmt_bytestring
             at src/libstd/panicking.rs:459
             at src/libstd/panic.rs:365
             at src/libstd/rt.rs:58
  28: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  29: tokiotest::main
```

Crate versions used:

```
tokio-core = "0.1.13"
tokio = "0.1.2"
futures = "0.1.18"
```

**Comment by carllerche** [comment]
I posted #314 which should fix. Can confirm in your use case.
